# render.yaml
services:
  - type: web
    name: participation_web
    env: python
    buildCommand: "./.render/build.sh"
    startCommand: "uvicorn backend.server:app --host=0.0.0.0 --port=10000"
    plan: free